spring.application.name=Team1_DASH_V
spring.profiles.active=dev
server.port=8080

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
spring.kafka.consumer.group-id=compliance-consumers
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.listener.missing-topics-fatal=false

cv.kafka.topic.email=clustered-email
cv.kafka.topic.slack=clustered-slack
cv.kafka.topic.policy=clustered-policy
cv.kafka.topic.violation=clustered-violation
cv.kafka.topic.evaluator=clustered-evaluator

# Mongo
spring.data.mongodb.uri=mongodb://localhost:27017/companyVault

# SQL (if using JPA entities)
spring.datasource.url=jdbc:postgresql://localhost:5432/team1db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Elasticsearch
spring.elasticsearch.uris=http://localhost:9200
cv.elasticsearch.index.policies=policies_index
cv.elasticsearch.index.violations=violations_index

# Storage
cv.storage.local.base-dir=C:/localstorage
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Security
security.internal.token=change-me-secret

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
logging.level.org.springframework.kafka=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
